
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 09 19:32:03 PDT 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 14;
  public static final int READ = 8;
  public static final int ELSE = 3;
  public static final int PLUS = 12;
  public static final int RPAREN = 17;
  public static final int SEMI = 11;
  public static final int END = 7;
  public static final int IF = 2;
  public static final int LPAREN = 16;
  public static final int ID = 19;
  public static final int BEGIN = 6;
  public static final int EQUALS = 10;
  public static final int NUMBER = 18;
  public static final int EOF = 0;
  public static final int DIVIDE = 15;
  public static final int MINUS = 13;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int FOR = 4;
  public static final int TO = 5;
}

